### ISSUE TITLE
ｇｅｎｅｒａｔｅ　ｔｈｅ　ｔｒａｉｎ　ｓａｍｐｌｅｓ 　ｇｅｔ　ＥＲＲＯＲ　

### ISSUE THREAD

**Issue by tzhang2014** [dlunion/mtcnn#18]
Ｈｅｌｌｏ，Ｄｅａｒ dlunion : 
   When ｉ run the script that gen_12net_data2．ｐｙ get follow ERROR,
Traceback (most recent call last):
  File "gen_12net_data.py", line 103, in <module>
    delta_x = npr.randint(-w * 0.2, w * 0.2)
  File "mtrand.pyx", line 1264, in mtrand.RandomState.randint (numpy/random/mtrand/mtrand.c:14492)
ValueError: low >= high

Can you help me ? Thx

**Comment by LeeRock** [comment]
referencing to https://groups.google.com/forum/#!topic/uic-mcs260-s13/fYGk4vDbJCs.
